### ISSUE TITLE
correction to the JSON filename

### ISSUE THREAD

**Issue by GianniPucillo** [diving-in/threejs#1]
Hi. First of all: great content, youtube video lesson included.

I'm opening this issue to ask the correction of the JSON file name "monkey_animated3.json": inside the index.html (line 51) is asked to be loaded with "monkey_animated3.json" name, while the filename in the ZIP file is "monkey_animated.json".

Thanks, Gianni.

**Comment by cjgammon** [comment]
Thanks for letting me know!

This should be fixed in 604de6a
